-- ============================================================================
-- iroiro 카탈로그 DB 스키마 — 토레카 마스터 데이터의 단일 진실(dev·prd 공유)
-- ============================================================================
-- 이 파일은 커머스 DB(db/schema.sql)와 **다른 데이터베이스**(iroiro_catalog)에 적용한다.
-- 토레카 마스터(그룹·멤버·시리즈·종류·카드)는 환경마다 중복 저장할 이유가 없어 한곳에 두고,
-- dev·prd 앱이 CATALOG_DATABASE_URL 로 같은 DB에 접속한다(2026-09-22 결정).
--
-- 규칙은 db/schema.sql 과 동일(docs/architecture/data-modeling.md):
--  - 앱은 비특권 `catalog_app` 롤로 접속하고 GRANT 매트릭스가 DB 방어선이다(RLS 미사용).
--  - FK 없음(relationMode=prisma). 커머스 테이블(product·favorite·post…)은 여기 id 를 값으로만 참조한다.
--  - 변경은 아래에 `-- [timestamp_name]` 섹션으로 덧붙이고, 문장은 재실행 안전(IF NOT EXISTS)하게 쓴다.
--  - Prisma 정본은 이 파일. prisma/catalog.prisma 는 `npm run db:pull:catalog` 파생물.
--
-- 로컬: compose.yaml 의 postgres 에 `iroiro_catalog` DB 를 만들고(docker/initdb) `npm run db:reset` 이 적용.
-- 운영: 운영 RDS(iroiro-prd) 안의 별도 DB. 절차는 docs/deployment.md §카탈로그 DB.
-- ============================================================================

-- [20260923000000_init_catalog_db]
-- ============================================================================

-- 앱 접속 롤 — LOGIN·비밀번호는 적용 스크립트가 별도로 부여한다(ALTER ROLE catalog_app WITH LOGIN PASSWORD ...).
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'catalog_app') THEN
        CREATE ROLE catalog_app NOLOGIN;
    END IF;
END
$$;

-- ── 그룹 ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS team
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT        NOT NULL,
    name_i18n     JSONB,
    debut_date    DATE,
    disband_date  DATE,
    display_order INTEGER,
    theme_color   TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by    TEXT
);

CREATE INDEX IF NOT EXISTS team_name_idx ON team (name);
CREATE INDEX IF NOT EXISTS team_display_order_idx ON team (display_order);
CREATE INDEX IF NOT EXISTS team_created_at_idx ON team (created_at);
CREATE INDEX IF NOT EXISTS team_updated_at_idx ON team (updated_at);

COMMENT ON TABLE team IS '팀/그룹';
COMMENT ON COLUMN team.name IS '한국어 그룹명';
COMMENT ON COLUMN team.name_i18n IS '다국어 그룹명 — {"ja-jpan","ja-hira","en"}';
COMMENT ON COLUMN team.debut_date IS '데뷔일';
COMMENT ON COLUMN team.disband_date IS '해체일';
COMMENT ON COLUMN team.display_order IS '그룹 노출 순서(1부터, 관리자 지정). NULL 은 맨 뒤. 운영 규칙: CUTIE STREET 1, 나머지 데뷔순';
COMMENT ON COLUMN team.theme_color IS '그룹 고유색 — #rrggbb. NULL 이면 기본 색';

-- ── 멤버 ────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS member
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    name_i18n   JSONB,
    debut_date  DATE,
    retire_date DATE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by  TEXT
);

CREATE INDEX IF NOT EXISTS member_name_idx ON member (name);
CREATE INDEX IF NOT EXISTS member_created_at_idx ON member (created_at);
CREATE INDEX IF NOT EXISTS member_updated_at_idx ON member (updated_at);

COMMENT ON TABLE member IS '멤버';
COMMENT ON COLUMN member.name IS '한국어 멤버명';
COMMENT ON COLUMN member.name_i18n IS '다국어 멤버명 — {"ja-jpan","ja-hira","en"}';
COMMENT ON COLUMN member.debut_date IS '데뷔일';
COMMENT ON COLUMN member.retire_date IS '은퇴일';

-- ── 팀-멤버 활동 이력 ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS team_member
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id           BIGINT      NOT NULL,
    member_id         BIGINT      NOT NULL,
    active_start_date DATE        NOT NULL,
    active_end_date   DATE,
    role              TEXT,
    display_order     INT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by        TEXT,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by        TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS team_member_active_member_team_unique ON team_member (member_id, team_id) WHERE active_end_date IS NULL;
CREATE INDEX IF NOT EXISTS team_member_active_idx ON team_member (team_id, member_id) WHERE active_end_date IS NULL;
CREATE INDEX IF NOT EXISTS team_member_team_order_idx ON team_member (team_id, display_order);
CREATE INDEX IF NOT EXISTS team_member_created_at_idx ON team_member (created_at);
CREATE INDEX IF NOT EXISTS team_member_updated_at_idx ON team_member (updated_at);

COMMENT ON TABLE team_member IS '팀-멤버 활동 이력';
COMMENT ON COLUMN team_member.active_start_date IS '활동 시작일';
COMMENT ON COLUMN team_member.active_end_date IS '활동 종료일(NULL 이면 현역)';
COMMENT ON COLUMN team_member.role IS '팀 내 역할';
COMMENT ON COLUMN team_member.display_order IS '그룹 내 공식 순번(1부터)';

-- ── 시리즈 종류 ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS series_kind
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key           TEXT        NOT NULL,
    label         TEXT        NOT NULL,
    display_order INTEGER     NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS series_kind_key_unique ON series_kind (key);
CREATE INDEX IF NOT EXISTS series_kind_created_at_idx ON series_kind (created_at);
CREATE INDEX IF NOT EXISTS series_kind_updated_at_idx ON series_kind (updated_at);

COMMENT ON TABLE series_kind IS '시리즈 종류(kind) 레지스트리 — 라벨·노출 순서를 관리자가 편집';
COMMENT ON COLUMN series_kind.key IS '종류 키 — series.kind 값(공백 포함 가능, 예: "CD benefits")';
COMMENT ON COLUMN series_kind.label IS '표시 라벨(한국어)';
COMMENT ON COLUMN series_kind.display_order IS '노출 순서(1부터, 관리자 지정)';

INSERT INTO series_kind (key, label, display_order) VALUES
    ('random',       '정규',    1),
    ('costume',      '의상',    2),
    ('event',        '이벤트',  3),
    ('birthday',     '생탄제',  4),
    ('season',       '시즌',    5),
    ('CD benefits',  'CD 특전', 6),
    ('kuji',         '쿠지',    7),
    ('sukisuki web', '웹 토레카', 8),
    ('others',       '기타',    99)
ON CONFLICT (key) DO NOTHING;

-- ── 시리즈 ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS series
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         TEXT        NOT NULL,
    team_id     BIGINT,
    kind        TEXT        NOT NULL,
    label       TEXT        NOT NULL,
    label_i18n  JSONB,
    product_url TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS series_sku_unique ON series (sku);
CREATE INDEX IF NOT EXISTS series_team_kind_idx ON series (team_id, kind);
CREATE INDEX IF NOT EXISTS series_created_at_idx ON series (created_at);

COMMENT ON TABLE series IS '시리즈 — 카드가 속하는 발매 단위(그룹→종류→시리즈)';
COMMENT ON COLUMN series.sku IS '시리즈 코드(예: CS-0225, usr-xxxx) — 유일';
COMMENT ON COLUMN series.team_id IS '소속 그룹 team.id (NULL 허용)';
COMMENT ON COLUMN series.kind IS '종류 — series_kind.key';
COMMENT ON COLUMN series.label IS '시리즈 이름 원문(대개 일본어)';
COMMENT ON COLUMN series.label_i18n IS '시리즈 이름 다국어 — {"ko": "…"} 한국어 병기';
COMMENT ON COLUMN series.product_url IS '공식 상품 페이지 URL(선택)';

-- ── 카드 ────────────────────────────────────────────────────────────────────
-- 토레카 마스터 — 판매물(product/used_listing)이 아닌 "카드 그 자체". 앞면 이미지 하나만 보관하며
-- 객체는 카탈로그 버킷(CATALOG_BUCKET)에 두 벌로 저장한다: cards/wm/<uuid>.jpg(공개·워터마크),
-- cards/clean/<uuid>.jpg(비공개·원본). front_r2_key 는 wm 키이고 clean 키는 규약으로 파생한다.
CREATE TABLE IF NOT EXISTS card
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code               TEXT,
    item_type               TEXT        NOT NULL DEFAULT 'photocard',
    team_id                 BIGINT,
    member_id               BIGINT,
    series_id               BIGINT,
    name                    TEXT        NOT NULL,
    description             TEXT,
    front_r2_key            TEXT,
    retail_price_jpy        INTEGER     NOT NULL DEFAULT 0,
    pose                    INTEGER     NOT NULL DEFAULT 1,
    status                  TEXT        NOT NULL DEFAULT 'active',
    submitted_by_account_id UUID,
    submitted_env           TEXT,
    review_note             TEXT,
    analysis_embedding      JSONB,
    analysis_model          TEXT,
    analyzed_at             TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT card_status_chk CHECK (status IN ('active', 'pending', 'rejected'))
);

CREATE INDEX IF NOT EXISTS card_team_member_idx ON card (team_id, member_id);
CREATE INDEX IF NOT EXISTS card_series_idx ON card (series_id);
CREATE INDEX IF NOT EXISTS card_status_idx ON card (status);
CREATE INDEX IF NOT EXISTS card_created_at_idx ON card (created_at);
CREATE INDEX IF NOT EXISTS card_analyzed_idx ON card (team_id, member_id) WHERE analyzed_at IS NOT NULL;

COMMENT ON TABLE card IS '토레카 마스터 (카드 원본 데이터) — dev·prd 공유';
COMMENT ON COLUMN card.item_code IS '아이템 코드(SKU 성격, 선택)';
COMMENT ON COLUMN card.item_type IS '아이템 종류 (photocard 등)';
COMMENT ON COLUMN card.name IS '카드 이름 — "멤버 · 시리즈" 규칙으로 자동 생성';
COMMENT ON COLUMN card.front_r2_key IS '앞면 워터마크 이미지 키(cards/wm/<uuid>.jpg). 원본은 cards/clean/<uuid>.jpg 로 파생';
COMMENT ON COLUMN card.retail_price_jpy IS '정가(엔)';
COMMENT ON COLUMN card.pose IS '포즈 번호 — 같은 (시리즈, 멤버) 내 1부터 순번';
COMMENT ON COLUMN card.status IS '상태 — active(공개)/pending(제보 검수 대기)/rejected(반려)';
COMMENT ON COLUMN card.submitted_by_account_id IS '제보한 회원 ID(제보 env 의 account.id) — NULL 이면 관리자 직접 등록';
COMMENT ON COLUMN card.submitted_env IS '제보가 들어온 환경(dev/prd/local) — 계정 id 는 환경별 DB 에 있으므로 같은 환경에서만 보상·표시';
COMMENT ON COLUMN card.review_note IS '검수 메모 (반려 사유 등)';
COMMENT ON COLUMN card.analysis_embedding IS '앞면(clean) 이미지 임베딩 벡터(JSONB float 배열, L2 정규화). 유사 카드 매칭용';
COMMENT ON COLUMN card.analysis_model IS '임베딩 생성 모델·버전 (예: amazon.titan-embed-image-v1)';
COMMENT ON COLUMN card.analyzed_at IS '이미지 분석 완료 시각. 미분석이면 NULL';

-- ── GRANT 매트릭스 — 앱 롤 catalog_app ──────────────────────────────────────
-- 카탈로그 공간의 관리자 CRUD + 유저 제보(card INSERT) + 등록 화면의 시리즈 즉석 추가(series INSERT).
GRANT USAGE ON SCHEMA public TO catalog_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON team, member, team_member, series, series_kind, card TO catalog_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO catalog_app;

-- ============================================================================
