-- ============================================================================
-- init_post: 자유게시판 도메인
-- ============================================================================

CREATE TABLE post
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id    UUID        NOT NULL,
    public_code   TEXT        NOT NULL,
    topic         TEXT        NOT NULL,
    title         TEXT        NOT NULL,
    body          TEXT        NOT NULL,
    edited_at     TIMESTAMPTZ,
    hidden_at     TIMESTAMPTZ,
    hidden_reason TEXT,
    hidden_by     TEXT,
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE post
    ADD CONSTRAINT post_hidden_consistency
        CHECK ((hidden_at IS NULL) = (hidden_reason IS NULL) AND (hidden_at IS NULL) = (hidden_by IS NULL));

CREATE UNIQUE INDEX post_public_code_unique ON post (public_code);
CREATE INDEX post_account_created_at_idx ON post (account_id, created_at);
CREATE INDEX post_created_at_idx ON post (created_at);
CREATE INDEX post_updated_at_idx ON post (updated_at);

COMMENT ON TABLE post IS '게시판 글';
COMMENT ON COLUMN post.id IS 'PK';
COMMENT ON COLUMN post.account_id IS '회원 ID';
COMMENT ON COLUMN post.public_code IS '공개 URL 코드';
COMMENT ON COLUMN post.topic IS '주제';
COMMENT ON COLUMN post.title IS '제목';
COMMENT ON COLUMN post.body IS '본문';
COMMENT ON COLUMN post.edited_at IS '콘텐츠 편집 시각';
COMMENT ON COLUMN post.hidden_at IS '숨김 시각';
COMMENT ON COLUMN post.hidden_reason IS '숨김 사유';
COMMENT ON COLUMN post.hidden_by IS '숨김 처리자';
COMMENT ON COLUMN post.deleted_at IS '삭제 시각';
COMMENT ON COLUMN post.created_at IS '생성일';
COMMENT ON COLUMN post.updated_at IS '수정일';

CREATE TABLE post_comment
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       BIGINT      NOT NULL,
    account_id    UUID        NOT NULL,
    parent_id     BIGINT,
    body          TEXT        NOT NULL,
    hidden_at     TIMESTAMPTZ,
    hidden_reason TEXT,
    hidden_by     TEXT,
    deleted_at    TIMESTAMPTZ,
    edited_at     TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE post_comment
    ADD CONSTRAINT post_comment_hidden_consistency
        CHECK ((hidden_at IS NULL) = (hidden_reason IS NULL) AND (hidden_at IS NULL) = (hidden_by IS NULL));

CREATE INDEX post_comment_post_idx ON post_comment (post_id);
CREATE INDEX post_comment_parent_idx ON post_comment (parent_id);
CREATE INDEX post_comment_account_created_at_idx ON post_comment (account_id, created_at); -- rate limit
CREATE INDEX post_comment_created_at_idx ON post_comment (created_at);
CREATE INDEX post_comment_updated_at_idx ON post_comment (updated_at);

COMMENT ON TABLE post_comment IS '게시판 댓글';
COMMENT ON COLUMN post_comment.id IS 'PK';
COMMENT ON COLUMN post_comment.post_id IS '글 ID';
COMMENT ON COLUMN post_comment.account_id IS '회원 ID';
COMMENT ON COLUMN post_comment.parent_id IS '부모 댓글 ID';
COMMENT ON COLUMN post_comment.body IS '내용';
COMMENT ON COLUMN post_comment.hidden_at IS '숨김 시각';
COMMENT ON COLUMN post_comment.hidden_reason IS '숨김 사유';
COMMENT ON COLUMN post_comment.hidden_by IS '숨김 처리자';
COMMENT ON COLUMN post_comment.deleted_at IS '삭제 시각';
COMMENT ON COLUMN post_comment.edited_at IS '본문 편집 시각';
COMMENT ON COLUMN post_comment.created_at IS '생성일';
COMMENT ON COLUMN post_comment.updated_at IS '수정일';

CREATE TABLE post_report
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id             BIGINT      NOT NULL,
    reporter_account_id UUID        NOT NULL,
    reason              TEXT        NOT NULL,
    detail              TEXT,
    snapshot            JSONB       NOT NULL,
    resolution          TEXT,
    resolved_by         TEXT,
    resolution_note     TEXT,
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE post_report
    ADD CONSTRAINT post_report_resolution_consistency
        CHECK ((resolved_at IS NULL) = (resolution IS NULL) AND (resolved_at IS NULL) = (resolved_by IS NULL));

CREATE UNIQUE INDEX post_report_post_reporter_unique ON post_report (post_id, reporter_account_id);
CREATE INDEX post_report_reporter_created_at_idx ON post_report (reporter_account_id, created_at); -- rate limit
CREATE INDEX post_report_unresolved_created_at_idx ON post_report (created_at) WHERE resolved_at IS NULL;
CREATE INDEX post_report_created_at_idx ON post_report (created_at);
CREATE INDEX post_report_updated_at_idx ON post_report (updated_at);

COMMENT ON TABLE post_report IS '글 신고';
COMMENT ON COLUMN post_report.id IS 'PK';
COMMENT ON COLUMN post_report.post_id IS '글 ID';
COMMENT ON COLUMN post_report.reporter_account_id IS '신고자 회원 ID';
COMMENT ON COLUMN post_report.reason IS '사유';
COMMENT ON COLUMN post_report.detail IS '상세 사유';
COMMENT ON COLUMN post_report.snapshot IS '신고 시점 대상 스냅샷';
COMMENT ON COLUMN post_report.resolution IS '처리 결과';
COMMENT ON COLUMN post_report.resolved_by IS '처리자 ';
COMMENT ON COLUMN post_report.resolution_note IS '처리 메모';
COMMENT ON COLUMN post_report.resolved_at IS '처리 시각';
COMMENT ON COLUMN post_report.created_at IS '생성일';
COMMENT ON COLUMN post_report.updated_at IS '수정일';

CREATE TABLE post_comment_report
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_id          BIGINT      NOT NULL,
    reporter_account_id UUID        NOT NULL,
    reason              TEXT        NOT NULL,
    detail              TEXT,
    snapshot            JSONB       NOT NULL,
    resolution          TEXT,
    resolved_by         TEXT,
    resolution_note     TEXT,
    resolved_at         TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE post_comment_report
    ADD CONSTRAINT post_comment_report_resolution_consistency
        CHECK ((resolved_at IS NULL) = (resolution IS NULL) AND (resolved_at IS NULL) = (resolved_by IS NULL));

CREATE UNIQUE INDEX post_comment_report_comment_reporter_unique ON post_comment_report (comment_id, reporter_account_id);
CREATE INDEX post_comment_report_reporter_created_at_idx ON post_comment_report (reporter_account_id, created_at);
CREATE INDEX post_comment_report_unresolved_created_at_idx ON post_comment_report (created_at) WHERE resolved_at IS NULL;
CREATE INDEX post_comment_report_created_at_idx ON post_comment_report (created_at);
CREATE INDEX post_comment_report_updated_at_idx ON post_comment_report (updated_at);

COMMENT ON TABLE post_comment_report IS '댓글 신고';
COMMENT ON COLUMN post_comment_report.id IS 'PK';
COMMENT ON COLUMN post_comment_report.comment_id IS '댓글 ID';
COMMENT ON COLUMN post_comment_report.reporter_account_id IS '신고자 회원 ID';
COMMENT ON COLUMN post_comment_report.reason IS '사유';
COMMENT ON COLUMN post_comment_report.detail IS '상세 사유';
COMMENT ON COLUMN post_comment_report.snapshot IS '신고 시점 대상 스냅샷';
COMMENT ON COLUMN post_comment_report.resolution IS '처리 결과';
COMMENT ON COLUMN post_comment_report.resolved_by IS '처리자';
COMMENT ON COLUMN post_comment_report.resolution_note IS '처리 메모';
COMMENT ON COLUMN post_comment_report.resolved_at IS '처리 시각';
COMMENT ON COLUMN post_comment_report.created_at IS '생성일';
COMMENT ON COLUMN post_comment_report.updated_at IS '수정일';

CREATE TABLE post_photo
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id       BIGINT      NOT NULL,
    r2_key        TEXT        NOT NULL,
    display_order INT         NOT NULL DEFAULT 0,
    is_thumbnail  BOOLEAN     NOT NULL DEFAULT false,
    deleted_at    TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX post_photo_r2_key_unique ON post_photo (r2_key);
CREATE UNIQUE INDEX post_photo_one_thumbnail_unique ON post_photo (post_id) WHERE is_thumbnail = true AND deleted_at IS NULL;
CREATE INDEX post_photo_post_idx ON post_photo (post_id, display_order);
CREATE INDEX post_photo_created_at_idx ON post_photo (created_at);
CREATE INDEX post_photo_updated_at_idx ON post_photo (updated_at);

COMMENT ON TABLE post_photo IS '게시판 글 사진';
COMMENT ON COLUMN post_photo.id IS 'PK';
COMMENT ON COLUMN post_photo.post_id IS '글 ID';
COMMENT ON COLUMN post_photo.r2_key IS 'R2 최종 객체 키';
COMMENT ON COLUMN post_photo.display_order IS '표시 순서';
COMMENT ON COLUMN post_photo.is_thumbnail IS '썸네일 여부';
COMMENT ON COLUMN post_photo.deleted_at IS '삭제 시각';
COMMENT ON COLUMN post_photo.created_at IS '생성일';
COMMENT ON COLUMN post_photo.updated_at IS '수정일';

CREATE TABLE pending_post_photo
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id   UUID        NOT NULL,
    r2_key       TEXT        NOT NULL,
    content_type TEXT        NOT NULL,
    size_bytes   INT         NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    consumed_at  TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE pending_post_photo
    ADD CONSTRAINT pending_post_photo_size_positive CHECK (size_bytes > 0);
CREATE UNIQUE INDEX pending_post_photo_r2_key_unique ON pending_post_photo (r2_key);
CREATE INDEX pending_post_photo_account_created_at_idx ON pending_post_photo (account_id, created_at);
CREATE INDEX pending_post_photo_expires_at_idx ON pending_post_photo (expires_at);
CREATE INDEX pending_post_photo_created_at_idx ON pending_post_photo (created_at);
CREATE INDEX pending_post_photo_updated_at_idx ON pending_post_photo (updated_at);

COMMENT ON TABLE pending_post_photo IS '등록 대기 사진';
COMMENT ON COLUMN pending_post_photo.id IS 'PK';
COMMENT ON COLUMN pending_post_photo.account_id IS '회원 ID';
COMMENT ON COLUMN pending_post_photo.r2_key IS 'R2 임시 객체 키';
COMMENT ON COLUMN pending_post_photo.content_type IS '선언 MIME';
COMMENT ON COLUMN pending_post_photo.size_bytes IS '선언 크기';
COMMENT ON COLUMN pending_post_photo.expires_at IS '만료 시각';
COMMENT ON COLUMN pending_post_photo.consumed_at IS '소비 시각';
COMMENT ON COLUMN pending_post_photo.created_at IS '생성일';
COMMENT ON COLUMN pending_post_photo.updated_at IS '수정일';

-- ============================================================================
-- GRANT — app 롤만. post·post_comment·post_photo는 DELETE 미부여(soft delete).
-- 신고는 컬럼 제한 UPDATE. pending_post_photo은 만료 행 정리 잡(후속)이 hard delete하므로 DELETE 부여.
-- ============================================================================
REVOKE ALL ON post, post_comment, post_report, post_comment_report, post_photo, pending_post_photo
    FROM anon, authenticated, app;
GRANT SELECT, INSERT, UPDATE ON post TO app;
GRANT SELECT, INSERT, UPDATE ON post_comment TO app;
GRANT SELECT, INSERT ON post_report TO app;
GRANT UPDATE (resolution, resolved_by, resolution_note, resolved_at, updated_at) ON post_report TO app;
GRANT SELECT, INSERT ON post_comment_report TO app;
GRANT UPDATE (resolution, resolved_by, resolution_note, resolved_at, updated_at) ON post_comment_report TO app;
GRANT SELECT, INSERT, UPDATE ON post_photo TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON pending_post_photo TO app;
