-- ============================================================================
-- add_used_trade: 유저 간 중고거래(C2C) — 매물·사진·입찰·거래 + 전역 설정
-- ============================================================================
-- 회사 판매(product)와 별개의 유저 등록 매물. 고정가/경매 모두 지원하며
-- 경매 필드·CHECK는 product의 auction 패턴을 그대로 따른다.
-- 기능 전체가 site_setting.used_trade_enabled 플래그 뒤에 숨는다(런칭 전 OFF).

-- site_setting — 디자인 테마 제거로 삭제됐던 싱글턴을 범용 설정으로 재도입.
CREATE TABLE site_setting
(
    id                 BIGINT PRIMARY KEY,
    used_trade_enabled BOOLEAN     NOT NULL DEFAULT false,
    used_trade_fee_bp  INT         NOT NULL DEFAULT 1000,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE site_setting
    ADD CONSTRAINT site_setting_singleton CHECK (id = 1),
    ADD CONSTRAINT site_setting_fee_bp_chk CHECK (used_trade_fee_bp BETWEEN 0 AND 5000);

INSERT INTO site_setting (id) VALUES (1);

COMMENT ON TABLE site_setting IS '사이트 전역 설정 — 항상 1행(singleton, CHECK id=1)';
COMMENT ON COLUMN site_setting.id IS 'PK — 항상 1';
COMMENT ON COLUMN site_setting.used_trade_enabled IS '중고거래 기능 노출 여부 — OFF면 고객 화면에서 완전히 숨김';
COMMENT ON COLUMN site_setting.used_trade_fee_bp IS '중고거래 판매 수수료(만분율, 1000=10%). 0~5000';
COMMENT ON COLUMN site_setting.created_at IS '생성일';
COMMENT ON COLUMN site_setting.updated_at IS '수정일';

-- 중고 매물 — 유저가 직접 등록. 카탈로그(그룹→멤버→종류→시리즈) 참조는 선택.
CREATE TABLE used_listing
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_account_id         UUID        NOT NULL,
    item_type                 TEXT        NOT NULL DEFAULT 'photocard',
    team_id                   BIGINT,
    member_id                 BIGINT,
    series_id                 BIGINT,
    source_product_id         BIGINT,
    title                     TEXT        NOT NULL,
    description               TEXT,
    condition                 TEXT        NOT NULL,
    sale_mode                 TEXT        NOT NULL DEFAULT 'fixed',
    price                     INT,
    shipping_method           TEXT        NOT NULL DEFAULT 'post',
    shipping_fee              INT         NOT NULL DEFAULT 0,
    status                    TEXT        NOT NULL DEFAULT 'active',
    auction_start_price       INT,
    auction_current_price     INT,
    auction_bid_count         INT         NOT NULL DEFAULT 0,
    auction_ends_at           TIMESTAMPTZ,
    auction_status            TEXT,
    auction_winner_account_id UUID,
    auction_pay_due_at        TIMESTAMPTZ,
    view_count                INT         NOT NULL DEFAULT 0,
    created_at                TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE used_listing
    ADD CONSTRAINT used_listing_sale_mode_chk CHECK (sale_mode IN ('fixed', 'auction')),
    ADD CONSTRAINT used_listing_status_chk
        CHECK (status IN ('active', 'reserved', 'sold', 'canceled', 'blocked')),
    ADD CONSTRAINT used_listing_shipping_chk
        CHECK (shipping_method IN ('post', 'parcel', 'direct')),
    ADD CONSTRAINT used_listing_price_chk
        CHECK (sale_mode = 'auction' OR (price IS NOT NULL AND price > 0)),
    ADD CONSTRAINT used_listing_auction_fields_chk CHECK (
        sale_mode = 'fixed'
        OR (
            auction_start_price IS NOT NULL
            AND auction_start_price > 0
            AND auction_ends_at IS NOT NULL
            AND auction_status IS NOT NULL
        )
    ),
    ADD CONSTRAINT used_listing_auction_status_chk
        CHECK (auction_status IS NULL OR auction_status IN ('live', 'awarded', 'passed'));

CREATE INDEX used_listing_status_created_idx ON used_listing (status, created_at DESC);
CREATE INDEX used_listing_seller_idx ON used_listing (seller_account_id, created_at DESC);
CREATE INDEX used_listing_series_idx ON used_listing (series_id);
CREATE INDEX used_listing_member_idx ON used_listing (member_id);
CREATE INDEX used_listing_auction_due_idx
    ON used_listing (auction_status, auction_ends_at)
    WHERE sale_mode = 'auction';

COMMENT ON TABLE used_listing IS '중고 매물 — 유저 등록. product(회사 판매)와 별개';
COMMENT ON COLUMN used_listing.id IS 'PK';
COMMENT ON COLUMN used_listing.seller_account_id IS '판매자 account.id';
COMMENT ON COLUMN used_listing.item_type IS '아이템 구분(photocard 등) — product와 동일 어휘';
COMMENT ON COLUMN used_listing.team_id IS '그룹 team.id (선택)';
COMMENT ON COLUMN used_listing.member_id IS '멤버 member.id (선택)';
COMMENT ON COLUMN used_listing.series_id IS '시리즈 series.id (선택) — 지정 시 카드 특정·시세 표시';
COMMENT ON COLUMN used_listing.source_product_id IS '동일 카드의 회사 카탈로그 product.id (선택)';
COMMENT ON COLUMN used_listing.title IS '매물 제목';
COMMENT ON COLUMN used_listing.description IS '설명';
COMMENT ON COLUMN used_listing.condition IS '상품 상태 — product condition과 동일 어휘(new~poor)';
COMMENT ON COLUMN used_listing.sale_mode IS '판매 방식: fixed | auction';
COMMENT ON COLUMN used_listing.price IS '고정가(KRW) — fixed 필수';
COMMENT ON COLUMN used_listing.shipping_method IS '배송 방법: post(우체국 준등기) | parcel(택배) | direct(직거래)';
COMMENT ON COLUMN used_listing.shipping_fee IS '배송비(KRW). 0 = 배송비 포함';
COMMENT ON COLUMN used_listing.status IS 'active(판매중) | reserved(거래중) | sold(판매완료) | canceled(취소) | blocked(관리자 차단)';
COMMENT ON COLUMN used_listing.auction_start_price IS '경매 시작가(KRW). auction 필수';
COMMENT ON COLUMN used_listing.auction_current_price IS '현재 최고 입찰가 — used_bid 최대값 캐시';
COMMENT ON COLUMN used_listing.auction_bid_count IS '누적 입찰 수 캐시';
COMMENT ON COLUMN used_listing.auction_ends_at IS '경매 마감 시각';
COMMENT ON COLUMN used_listing.auction_status IS 'live | awarded | passed';
COMMENT ON COLUMN used_listing.auction_winner_account_id IS '낙찰자 account.id';
COMMENT ON COLUMN used_listing.auction_pay_due_at IS '낙찰자 결제 기한';
COMMENT ON COLUMN used_listing.view_count IS '조회수';
COMMENT ON COLUMN used_listing.created_at IS '생성일';
COMMENT ON COLUMN used_listing.updated_at IS '수정일';

-- 매물 사진 — 유저 업로드(복수). 대표사진은 정확히 1장.
CREATE TABLE used_listing_photo
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id    BIGINT      NOT NULL,
    r2_key        TEXT        NOT NULL,
    display_order INT         NOT NULL DEFAULT 0,
    is_primary    BOOLEAN     NOT NULL DEFAULT false,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX used_listing_photo_primary_unique
    ON used_listing_photo (listing_id) WHERE (is_primary = true);
CREATE INDEX used_listing_photo_listing_idx ON used_listing_photo (listing_id, display_order);

COMMENT ON TABLE used_listing_photo IS '중고 매물 사진 — 유저 업로드';
COMMENT ON COLUMN used_listing_photo.id IS 'PK';
COMMENT ON COLUMN used_listing_photo.listing_id IS '매물 used_listing.id';
COMMENT ON COLUMN used_listing_photo.r2_key IS 'R2 객체 키';
COMMENT ON COLUMN used_listing_photo.display_order IS '노출 순서';
COMMENT ON COLUMN used_listing_photo.is_primary IS '대표사진 — 매물당 1장(부분 유니크)';
COMMENT ON COLUMN used_listing_photo.created_at IS '생성일';

-- 중고 경매 입찰 원장 — auction_bid와 동일 패턴(INSERT만).
CREATE TABLE used_bid
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    listing_id BIGINT      NOT NULL,
    account_id UUID        NOT NULL,
    amount     INT         NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE used_bid
    ADD CONSTRAINT used_bid_amount_positive CHECK (amount > 0);

CREATE INDEX used_bid_listing_idx ON used_bid (listing_id, amount DESC, id ASC);
CREATE INDEX used_bid_account_idx ON used_bid (account_id, created_at DESC);

COMMENT ON TABLE used_bid IS '중고 경매 입찰 원장';
COMMENT ON COLUMN used_bid.id IS 'PK';
COMMENT ON COLUMN used_bid.listing_id IS '매물 used_listing.id';
COMMENT ON COLUMN used_bid.account_id IS '입찰자 account.id';
COMMENT ON COLUMN used_bid.amount IS '입찰가(KRW)';
COMMENT ON COLUMN used_bid.created_at IS '입찰 시각';

-- 중고 거래 — 구매 확정 시 1건. 수수료율은 거래 시점 스냅샷(설정 변경과 무관).
CREATE TABLE used_trade
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id         BIGINT      NOT NULL,
    buyer_account_id   UUID        NOT NULL,
    seller_account_id  UUID        NOT NULL,
    price              INT         NOT NULL,
    shipping_fee       INT         NOT NULL DEFAULT 0,
    fee_bp             INT         NOT NULL,
    fee_amount         INT         NOT NULL,
    seller_payout      INT         NOT NULL,
    status             TEXT        NOT NULL DEFAULT 'pending',
    recipient_name     TEXT,
    recipient_phone    TEXT,
    recipient_address  TEXT,
    post_tracking_code TEXT,
    post_qr_issued_at  TIMESTAMPTZ,
    completed_at       TIMESTAMPTZ,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE used_trade
    ADD CONSTRAINT used_trade_status_chk
        CHECK (status IN ('pending', 'paid', 'shipped', 'completed', 'canceled')),
    ADD CONSTRAINT used_trade_amounts_chk
        CHECK (price > 0 AND fee_amount >= 0 AND seller_payout >= 0);

CREATE UNIQUE INDEX used_trade_listing_unique ON used_trade (listing_id)
    WHERE (status <> 'canceled');
CREATE INDEX used_trade_buyer_idx ON used_trade (buyer_account_id, created_at DESC);
CREATE INDEX used_trade_seller_idx ON used_trade (seller_account_id, created_at DESC);
CREATE INDEX used_trade_status_idx ON used_trade (status, created_at DESC);

COMMENT ON TABLE used_trade IS '중고 거래 — 매물당 유효 거래 1건(취소 제외)';
COMMENT ON COLUMN used_trade.id IS 'PK';
COMMENT ON COLUMN used_trade.listing_id IS '매물 used_listing.id';
COMMENT ON COLUMN used_trade.buyer_account_id IS '구매자 account.id';
COMMENT ON COLUMN used_trade.seller_account_id IS '판매자 account.id (비정규화)';
COMMENT ON COLUMN used_trade.price IS '거래가(KRW) — 고정가 또는 낙찰가';
COMMENT ON COLUMN used_trade.shipping_fee IS '배송비(KRW) 스냅샷';
COMMENT ON COLUMN used_trade.fee_bp IS '수수료율(만분율) — 거래 시점 site_setting 스냅샷';
COMMENT ON COLUMN used_trade.fee_amount IS '플랫폼 수수료(KRW) = price × fee_bp / 10000 반올림';
COMMENT ON COLUMN used_trade.seller_payout IS '판매자 정산액(KRW) = price + shipping_fee − fee_amount';
COMMENT ON COLUMN used_trade.status IS 'pending(결제대기) | paid(결제완료) | shipped(발송) | completed(수령확정) | canceled(취소)';
COMMENT ON COLUMN used_trade.recipient_name IS '수령인 이름';
COMMENT ON COLUMN used_trade.recipient_phone IS '수령인 연락처';
COMMENT ON COLUMN used_trade.recipient_address IS '배송지 주소';
COMMENT ON COLUMN used_trade.post_tracking_code IS '우체국 등기번호 — QR 발급 목업이 채움';
COMMENT ON COLUMN used_trade.post_qr_issued_at IS '우체국 QR 발급 시각(목업)';
COMMENT ON COLUMN used_trade.completed_at IS '수령 확정 시각';
COMMENT ON COLUMN used_trade.created_at IS '생성일';
COMMENT ON COLUMN used_trade.updated_at IS '수정일';
