-- ============================================================================
-- init_wishlist_banner_setting: 찜 · 배너 · 사이트 전역 설정
-- ============================================================================

CREATE TABLE wishlist
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id UUID        NOT NULL,
    product_id BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX wishlist_account_product_unique ON wishlist (account_id, product_id);
CREATE INDEX wishlist_product_idx ON wishlist (product_id);
CREATE INDEX wishlist_account_created_idx ON wishlist (account_id, created_at);

COMMENT ON TABLE wishlist IS '찜';
COMMENT ON COLUMN wishlist.id IS 'PK';
COMMENT ON COLUMN wishlist.account_id IS '회원 ID';
COMMENT ON COLUMN wishlist.product_id IS '상품 ID';
COMMENT ON COLUMN wishlist.created_at IS '생성일';

CREATE TABLE banner
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      TEXT        NOT NULL,
    image_key  TEXT        NOT NULL,
    link_url   TEXT        NOT NULL,
    starts_at  TIMESTAMPTZ,
    ends_at    TIMESTAMPTZ,
    sort_order INT         NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX banner_sort_order_idx ON banner (sort_order);
CREATE INDEX banner_created_at_idx ON banner (created_at);
CREATE INDEX banner_updated_at_idx ON banner (updated_at);

COMMENT ON TABLE banner IS '배너';
COMMENT ON COLUMN banner.id IS 'PK';
COMMENT ON COLUMN banner.title IS '배너 제목';
COMMENT ON COLUMN banner.image_key IS '이미지 키';
COMMENT ON COLUMN banner.link_url IS '이동 URL';
COMMENT ON COLUMN banner.starts_at IS '게시 시작 시각';
COMMENT ON COLUMN banner.ends_at IS '게시 종료 시각';
COMMENT ON COLUMN banner.sort_order IS '노출 순서';
COMMENT ON COLUMN banner.created_at IS '생성일';
COMMENT ON COLUMN banner.updated_at IS '수정일';

CREATE TABLE site_setting
(
    id            BIGINT PRIMARY KEY,
    active_design TEXT        NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE site_setting
    ADD CONSTRAINT site_setting_singleton CHECK (id = 1);

INSERT INTO site_setting (id, active_design)
VALUES (1, 'game');

COMMENT ON TABLE site_setting IS '사이트 전역 설정';
COMMENT ON COLUMN site_setting.id IS 'PK';
COMMENT ON COLUMN site_setting.active_design IS '활성 디자인 테마';
COMMENT ON COLUMN site_setting.created_at IS '생성일';
COMMENT ON COLUMN site_setting.updated_at IS '수정일';

REVOKE ALL ON wishlist, banner, site_setting FROM anon, authenticated, app;

-- wishlist : 찜 토글(생성·해제)이라 UPDATE 불필요
GRANT SELECT, INSERT, DELETE ON wishlist TO app;
-- banner : 관리자 CRUD
GRANT SELECT, INSERT, UPDATE, DELETE ON banner TO app;
-- site_setting : 싱글턴 upsert(INSERT+UPDATE). 행 삭제는 없으므로 DELETE 미부여
GRANT SELECT, INSERT, UPDATE ON site_setting TO app;
