-- ============================================================================
-- add_series_catalog: 카탈로그 계층(그룹→멤버→종류→시리즈) + 외부 시세 저장
-- ============================================================================
-- 외부 분석기(Cutie Card)의 시리즈·시세를 버리지 않고 보관한다.
-- 시리즈는 외부 sku가 단일 진실 — 임포트 시 find-or-create로 자동 생성된다.
-- product는 시리즈 참조 + 시세 스냅샷을 갖고, 검색·추천·중고 시세 표시에 쓴다.

CREATE TABLE series
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku         TEXT        NOT NULL,
    team_id     BIGINT,
    kind        TEXT        NOT NULL,
    label       TEXT        NOT NULL,
    product_url TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX series_sku_unique ON series (sku);
CREATE INDEX series_team_kind_idx ON series (team_id, kind);
CREATE INDEX series_created_at_idx ON series (created_at);

COMMENT ON TABLE series IS '시리즈 — 카탈로그 계층의 최하위(그룹→멤버→종류→시리즈)';
COMMENT ON COLUMN series.id IS 'PK';
COMMENT ON COLUMN series.sku IS '외부 시리즈 코드(예: CS-0225) — 임포트 멱등 키';
COMMENT ON COLUMN series.team_id IS '소속 그룹 team.id (외부 데이터 기준, NULL 허용)';
COMMENT ON COLUMN series.kind IS '종류: random | costume | event | birthday 등 (외부 어휘 추종)';
COMMENT ON COLUMN series.label IS '표시명(예: ver.7, たすき衣装)';
COMMENT ON COLUMN series.product_url IS '공식 판매 페이지 URL';
COMMENT ON COLUMN series.created_at IS '생성일';
COMMENT ON COLUMN series.updated_at IS '수정일';

-- product — 시리즈 참조 + 외부 시세 스냅샷(임포트/갱신 시 채움).
ALTER TABLE product
    ADD COLUMN series_id         BIGINT,
    ADD COLUMN market_avg_jpy    INT NOT NULL DEFAULT 0,
    ADD COLUMN market_min_jpy    INT NOT NULL DEFAULT 0,
    ADD COLUMN market_max_jpy    INT NOT NULL DEFAULT 0,
    ADD COLUMN market_sold_count INT NOT NULL DEFAULT 0,
    ADD COLUMN retail_price_jpy  INT NOT NULL DEFAULT 0;

CREATE INDEX product_series_idx ON product (series_id);

COMMENT ON COLUMN product.series_id IS '시리즈 참조 series.id — 같은 카드 매물 묶음·추천의 기준';
COMMENT ON COLUMN product.market_avg_jpy IS '외부 시세 평균(JPY) — 임포트 시 스냅샷';
COMMENT ON COLUMN product.market_min_jpy IS '외부 시세 최저(JPY)';
COMMENT ON COLUMN product.market_max_jpy IS '외부 시세 최고(JPY)';
COMMENT ON COLUMN product.market_sold_count IS '외부 거래 건수';
COMMENT ON COLUMN product.retail_price_jpy IS '공식 정가(JPY)';
