-- ============================================================================
-- init_account: 회원 · 자체 인증 도메인
--   - account = 신원 단일 진실, id = 앱 생성 UUIDv7(포터블)
-- ============================================================================

CREATE TABLE account
(
    id                       UUID PRIMARY KEY,
    email                    TEXT,
    email_verified_at        TIMESTAMPTZ,
    phone_number             TEXT,
    phone_number_verified_at TIMESTAMPTZ,
    display_name             TEXT        NOT NULL,
    public_code              TEXT        NOT NULL,
    avatar_key               TEXT,
    deleted_at               TIMESTAMPTZ,
    is_admin                 BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX account_email_idx ON account (email) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX account_phone_number_verified_uq ON account (phone_number) WHERE phone_number_verified_at IS NOT NULL;
CREATE UNIQUE INDEX account_public_code_unique ON account (public_code);
CREATE INDEX account_created_at_idx ON account (created_at);
CREATE INDEX account_updated_at_idx ON account (updated_at);

COMMENT ON TABLE account IS '회원';
COMMENT ON COLUMN account.id IS 'PK(UUID)';
COMMENT ON COLUMN account.email IS '이메일';
COMMENT ON COLUMN account.email_verified_at IS '이메일 검증시각';
COMMENT ON COLUMN account.phone_number IS '전화번호';
COMMENT ON COLUMN account.phone_number_verified_at IS '전화번호 검증시각';
COMMENT ON COLUMN account.display_name IS '표시명';
COMMENT ON COLUMN account.public_code IS '공개 작성자 코드';
COMMENT ON COLUMN account.avatar_key IS '아바타 객체 키';
COMMENT ON COLUMN account.deleted_at IS '탈퇴 시각';
COMMENT ON COLUMN account.is_admin IS '어드민 여부';
COMMENT ON COLUMN account.created_at IS '생성일';
COMMENT ON COLUMN account.updated_at IS '수정일';

CREATE TABLE account_identity
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id       UUID        NOT NULL,
    provider         TEXT        NOT NULL,
    provider_user_id TEXT        NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX account_identity_provider_uq ON account_identity (provider, provider_user_id);
CREATE INDEX account_identity_account_idx ON account_identity (account_id);
CREATE INDEX account_identity_created_at_idx ON account_identity (created_at);

COMMENT ON TABLE account_identity IS 'OAuth 신원';
COMMENT ON COLUMN account_identity.id IS 'PK';
COMMENT ON COLUMN account_identity.account_id IS '회원 ID';
COMMENT ON COLUMN account_identity.provider IS '제공자';
COMMENT ON COLUMN account_identity.provider_user_id IS '제공자 고유 식별자';
COMMENT ON COLUMN account_identity.created_at IS '생성일';

CREATE TABLE account_session
(
    token_hash TEXT PRIMARY KEY,
    account_id UUID        NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX account_session_account_idx ON account_session (account_id);
CREATE INDEX account_session_expires_idx ON account_session (expires_at);
CREATE INDEX account_session_created_at_idx ON account_session (created_at);

COMMENT ON TABLE account_session IS '회원 세션';
COMMENT ON COLUMN account_session.token_hash IS '세션 토큰 해시';
COMMENT ON COLUMN account_session.account_id IS '회원 ID';
COMMENT ON COLUMN account_session.expires_at IS '만료 시각';
COMMENT ON COLUMN account_session.created_at IS '생성일';

CREATE TABLE pending_account
(
    token_hash       TEXT PRIMARY KEY,
    provider         TEXT        NOT NULL,
    provider_user_id TEXT        NOT NULL,
    email            TEXT,
    display_name     TEXT,
    expires_at       TIMESTAMPTZ NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX pending_account_expires_idx ON pending_account (expires_at);
CREATE INDEX pending_account_created_at_idx ON pending_account (created_at);

COMMENT ON TABLE pending_account IS '가입 대기 회원';
COMMENT ON COLUMN pending_account.token_hash IS '가입 토큰 해시';
COMMENT ON COLUMN pending_account.provider IS '제공자';
COMMENT ON COLUMN pending_account.provider_user_id IS '제공자 고유 식별자';
COMMENT ON COLUMN pending_account.email IS '이메일';
COMMENT ON COLUMN pending_account.display_name IS '표시명';
COMMENT ON COLUMN pending_account.expires_at IS '만료 시각';
COMMENT ON COLUMN pending_account.created_at IS '생성일';

REVOKE ALL ON account, account_identity, account_session, pending_account FROM anon, authenticated, app;

-- account : 테이블 레벨 GRANT. 본인 행 한정은 앱 DAL이 담당(WHERE account_id = 세션).
GRANT SELECT, INSERT, UPDATE ON account TO app;
GRANT SELECT, INSERT, DELETE ON account_identity TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON account_session TO app;
GRANT SELECT, INSERT, DELETE ON pending_account TO app;
