-- ============================================================================
-- init_notice: 공지사항 도메인
-- ============================================================================

CREATE TABLE notice
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_code TEXT        NOT NULL,
    category    TEXT        NOT NULL,
    title       TEXT        NOT NULL,
    body        TEXT        NOT NULL,
    is_pinned   BOOLEAN     NOT NULL DEFAULT false,
    deleted_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by  TEXT
);

CREATE UNIQUE INDEX notice_public_code_unique ON notice (public_code);
CREATE INDEX notice_created_at_idx ON notice (created_at);
CREATE INDEX notice_updated_at_idx ON notice (updated_at);

COMMENT ON TABLE notice IS '공지사항';
COMMENT ON COLUMN notice.id IS 'PK';
COMMENT ON COLUMN notice.public_code IS '공개 URL 코드';
COMMENT ON COLUMN notice.category IS '카테고리';
COMMENT ON COLUMN notice.title IS '제목';
COMMENT ON COLUMN notice.body IS '본문';
COMMENT ON COLUMN notice.is_pinned IS '상단 고정 여부';
COMMENT ON COLUMN notice.deleted_at IS '삭제 시각';
COMMENT ON COLUMN notice.created_at IS '생성일';
COMMENT ON COLUMN notice.created_by IS '생성자';
COMMENT ON COLUMN notice.updated_at IS '수정일';
COMMENT ON COLUMN notice.updated_by IS '수정자';

CREATE TABLE notice_photo
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notice_id     BIGINT      NOT NULL,
    r2_key        TEXT        NOT NULL,
    display_order INT         NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX notice_photo_notice_id_idx ON notice_photo (notice_id, display_order);
CREATE UNIQUE INDEX notice_photo_r2_key_unique ON notice_photo (r2_key);
CREATE INDEX notice_photo_created_at_idx ON notice_photo (created_at);

COMMENT ON TABLE notice_photo IS '공지 첨부 사진';
COMMENT ON COLUMN notice_photo.id IS 'PK';
COMMENT ON COLUMN notice_photo.notice_id IS '공지 ID';
COMMENT ON COLUMN notice_photo.r2_key IS 'R2 객체 키';
COMMENT ON COLUMN notice_photo.display_order IS '표시 순서';
COMMENT ON COLUMN notice_photo.created_at IS '생성일';

-- ============================================================================
-- GRANT — app 롤만(Data API 미노출).
--   - notice       : DELETE 미부여(soft delete 강제)
--   - notice_photo : 전체 교체(delete+insert) 패턴이라 행 불변 → UPDATE 미부여
-- ============================================================================
REVOKE ALL ON notice, notice_photo FROM anon, authenticated, app;
GRANT SELECT, INSERT, UPDATE ON notice TO app;
GRANT SELECT, INSERT, DELETE ON notice_photo TO app;
