-- ============================================================================
-- init_catalog: 굿즈 카탈로그 도메인 부트스트랩
-- ============================================================================

CREATE TABLE team
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT        NOT NULL,
    name_i18n    JSONB,
    debut_date   DATE,
    disband_date DATE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by   TEXT,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by   TEXT
);

CREATE INDEX team_name_idx ON team (name);
CREATE INDEX team_created_at_idx ON team (created_at);
CREATE INDEX team_updated_at_idx ON team (updated_at);

COMMENT ON TABLE team IS '팀/그룹';
COMMENT ON COLUMN team.id IS 'PK';
COMMENT ON COLUMN team.name IS '한국어 그룹명';
COMMENT ON COLUMN team.name_i18n IS '다국어 그룹명';
COMMENT ON COLUMN team.debut_date IS '데뷔일';
COMMENT ON COLUMN team.disband_date IS '해체일';
COMMENT ON COLUMN team.created_at IS '생성일';
COMMENT ON COLUMN team.created_by IS '생성자';
COMMENT ON COLUMN team.updated_at IS '수정일';
COMMENT ON COLUMN team.updated_by IS '수정자';

CREATE TABLE member
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    name_i18n   JSONB,
    debut_date  DATE,
    retire_date DATE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by  TEXT,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by  TEXT
);

CREATE INDEX member_name_idx ON member (name);
CREATE INDEX member_created_at_idx ON member (created_at);
CREATE INDEX member_updated_at_idx ON member (updated_at);

COMMENT ON TABLE member IS '멤버';
COMMENT ON COLUMN member.id IS 'PK';
COMMENT ON COLUMN member.name IS '한국어 멤버명';
COMMENT ON COLUMN member.name_i18n IS '다국어 멤버명';
COMMENT ON COLUMN member.debut_date IS '데뷔일';
COMMENT ON COLUMN member.retire_date IS '은퇴일';
COMMENT ON COLUMN member.created_at IS '생성일';
COMMENT ON COLUMN member.created_by IS '생성자';
COMMENT ON COLUMN member.updated_at IS '수정일';
COMMENT ON COLUMN member.updated_by IS '수정자';

CREATE TABLE team_member
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id           BIGINT      NOT NULL,
    member_id         BIGINT      NOT NULL,
    active_start_date DATE        NOT NULL,
    active_end_date   DATE,
    role              TEXT,
    display_order     INT,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by        TEXT,
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by        TEXT
);

CREATE UNIQUE INDEX team_member_active_member_team_unique ON team_member (member_id, team_id) WHERE active_end_date IS NULL;
CREATE INDEX team_member_active_idx ON team_member (team_id, member_id) WHERE active_end_date IS NULL;
CREATE INDEX team_member_team_order_idx ON team_member (team_id, display_order);
CREATE INDEX team_member_created_at_idx ON team_member (created_at);
CREATE INDEX team_member_updated_at_idx ON team_member (updated_at);

COMMENT ON TABLE team_member IS '팀-멤버 활동 이력';
COMMENT ON COLUMN team_member.id IS 'PK';
COMMENT ON COLUMN team_member.team_id IS '팀 ID';
COMMENT ON COLUMN team_member.member_id IS '멤버 ID';
COMMENT ON COLUMN team_member.active_start_date IS '활동 시작일';
COMMENT ON COLUMN team_member.active_end_date IS '활동 종료일';
COMMENT ON COLUMN team_member.role IS '팀 내 역할';
COMMENT ON COLUMN team_member.display_order IS '팀 내 멤버 정렬 순서';
COMMENT ON COLUMN team_member.created_at IS '생성일';
COMMENT ON COLUMN team_member.created_by IS '생성자';
COMMENT ON COLUMN team_member.updated_at IS '수정일';
COMMENT ON COLUMN team_member.updated_by IS '수정자';

CREATE TABLE product
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_code              TEXT,
    source_id              TEXT,
    item_type              TEXT          NOT NULL,
    team_id                BIGINT,
    member_id              BIGINT,
    name                   TEXT          NOT NULL,
    description            TEXT,
    purchase_price_jpy     INT           NOT NULL,
    purchase_exchange_rate NUMERIC(8, 4) NOT NULL,
    purchase_price_krw     INT           NOT NULL,
    packaging_cost_krw     INT           NOT NULL DEFAULT 0,
    overseas_shipping_krw  INT           NOT NULL DEFAULT 0,
    domestic_shipping_krw  INT           NOT NULL DEFAULT 0,
    other_cost_krw         INT           NOT NULL DEFAULT 0,
    purchaser              TEXT,
    purchase_date          DATE          NOT NULL,
    regular_price          INT           NOT NULL,
    sale_price             INT           NOT NULL,
    condition              TEXT,
    stock_quantity         INT           NOT NULL DEFAULT 0,
    sale_status            TEXT          NOT NULL,
    created_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by             TEXT,
    updated_at             TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_by             TEXT
);

ALTER TABLE product
    ADD CONSTRAINT product_stock_non_negative CHECK (stock_quantity >= 0),
    ADD CONSTRAINT product_packaging_cost_non_negative CHECK (packaging_cost_krw >= 0),
    ADD CONSTRAINT product_overseas_shipping_non_negative CHECK (overseas_shipping_krw >= 0),
    ADD CONSTRAINT product_domestic_shipping_non_negative CHECK (domestic_shipping_krw >= 0),
    ADD CONSTRAINT product_other_cost_non_negative CHECK (other_cost_krw >= 0);

CREATE UNIQUE INDEX product_item_code_unique ON product (item_code, item_type, condition) WHERE item_code IS NOT NULL;
CREATE UNIQUE INDEX product_source_id_unique ON product (source_id) WHERE source_id IS NOT NULL;
CREATE INDEX product_purchaser_idx ON product (purchaser);
CREATE INDEX product_sale_status_team_idx ON product (sale_status, team_id);
CREATE INDEX product_sale_status_member_idx ON product (sale_status, member_id);
CREATE INDEX product_sale_status_item_type_idx ON product (sale_status, item_type);
CREATE INDEX product_sale_status_created_at_idx ON product (sale_status, created_at);
CREATE INDEX product_created_at_idx ON product (created_at);
CREATE INDEX product_updated_at_idx ON product (updated_at);
CREATE INDEX product_sale_price_idx ON product (sale_price);

COMMENT ON TABLE product IS '굿즈 상품';
COMMENT ON COLUMN product.id IS 'PK';
COMMENT ON COLUMN product.item_code IS '아이템 자체 식별 코드';
COMMENT ON COLUMN product.source_id IS '외부 분석기 카드 고유 ID';
COMMENT ON COLUMN product.item_type IS '아이템 유형';
COMMENT ON COLUMN product.team_id IS '팀 ID';
COMMENT ON COLUMN product.member_id IS '멤버 ID';
COMMENT ON COLUMN product.name IS '상품명';
COMMENT ON COLUMN product.description IS '상품 설명';
COMMENT ON COLUMN product.purchase_price_jpy IS '매입가 (엔)';
COMMENT ON COLUMN product.purchase_exchange_rate IS '매입 시점 100엔당 원화 환율';
COMMENT ON COLUMN product.purchase_price_krw IS '매입가 (원화)';
COMMENT ON COLUMN product.packaging_cost_krw IS '포장 부대비용 (원화)';
COMMENT ON COLUMN product.overseas_shipping_krw IS '해외 배송 부대비용 (원화)';
COMMENT ON COLUMN product.domestic_shipping_krw IS '국내 배송 부대비용 (원화)';
COMMENT ON COLUMN product.other_cost_krw IS '기타 부대비용 (원화)';
COMMENT ON COLUMN product.purchaser IS '매입자 (매입자별 정산 집계용)';
COMMENT ON COLUMN product.purchase_date IS '매입일';
COMMENT ON COLUMN product.regular_price IS '정가';
COMMENT ON COLUMN product.sale_price IS '실판매가';
COMMENT ON COLUMN product.condition IS '상품 상태 ';
COMMENT ON COLUMN product.stock_quantity IS '재고 수량';
COMMENT ON COLUMN product.sale_status IS '판매 상태';
COMMENT ON COLUMN product.created_at IS '생성일';
COMMENT ON COLUMN product.created_by IS '생성자';
COMMENT ON COLUMN product.updated_at IS '수정일';
COMMENT ON COLUMN product.updated_by IS '수정자';

CREATE TABLE product_photo
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT      NOT NULL,
    r2_key        TEXT        NOT NULL,
    alt_text      TEXT,
    display_order INT         NOT NULL DEFAULT 0,
    is_thumbnail  BOOLEAN     NOT NULL DEFAULT false,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by    TEXT,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by    TEXT
);

CREATE UNIQUE INDEX product_photo_one_thumbnail_unique ON product_photo (product_id) WHERE is_thumbnail = true;
CREATE INDEX product_photo_product_idx ON product_photo (product_id, display_order);
CREATE INDEX product_photo_created_at_idx ON product_photo (created_at);
CREATE INDEX product_photo_updated_at_idx ON product_photo (updated_at);

COMMENT ON TABLE product_photo IS '굿즈 상품 사진';
COMMENT ON COLUMN product_photo.id IS 'PK';
COMMENT ON COLUMN product_photo.product_id IS '굿즈 상품 ID';
COMMENT ON COLUMN product_photo.r2_key IS 'Cloudflare R2 객체 키';
COMMENT ON COLUMN product_photo.alt_text IS '접근성 alt 텍스트';
COMMENT ON COLUMN product_photo.display_order IS '사진 노출 순서';
COMMENT ON COLUMN product_photo.is_thumbnail IS '썸네일 여부';
COMMENT ON COLUMN product_photo.created_at IS '생성일';
COMMENT ON COLUMN product_photo.created_by IS '생성자';
COMMENT ON COLUMN product_photo.updated_at IS '수정일';
COMMENT ON COLUMN product_photo.updated_by IS '수정자';

-- ============================================================================
-- 롤 · GRANT — 이 프로젝트의 DB 방어선(RLS 미사용, docs/architecture/db-authorization-review.md)
--   - app : 앱 전용 비특권 롤. Prisma가 이 롤로 접속해야 GRANT가 적용된다.
--           소유자(postgres)는 GRANT 대상이 아니라 전권을 가지므로, 전환 전까지 아래 설계는 무효다.
--   - 읽기는 anon/authenticated(Data API)+app, 쓰기는 app만. admin 판정은 앱 DAL(requireAdmin).
--   - TRUNCATE 미부여 : 테이블 전체를 즉시 비우므로 심층방어로 제외. 행 삭제는 DELETE로만
--           (그래서 GRANT는 ALL이 아닌 명시 권한).
--   - identity 컬럼이라 시퀀스 별도 GRANT 불필요 : GENERATED AS IDENTITY의 시퀀스는 컬럼에 종속돼
--           테이블 INSERT 권한만으로 동작(구식 serial이면 GRANT USAGE ON SEQUENCE를 따로 줘야 함).
-- ============================================================================
-- 포터빌리티: anon/authenticated는 Supabase 전용 롤이라 vanilla Postgres엔 없음 →
--   아래 REVOKE/GRANT가 "role does not exist"로 실패하지 않도록 없으면 NOLOGIN 스텁 생성.
DO
$$
    DECLARE
        r TEXT;
    BEGIN
        FOREACH r IN ARRAY ARRAY ['app', 'anon', 'authenticated']
            LOOP
                IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = r) THEN
                    EXECUTE format('CREATE ROLE %I NOLOGIN', r);
                END IF;
            END LOOP;
    END
$$;

-- ----------------------------------------------------------------------------
-- ⚠️ app 롤 LOGIN 부여 — 이 마이그레이션에 넣지 않는 수동 단계
--
--   위 CREATE ROLE은 NOLOGIN(권한 그릇)이라 접속할 수 없다. 앱이 이 롤로 붙으려면
--   환경마다 아래를 1회 실행해야 한다. 비밀번호가 들어가므로 버전관리에 두지 않는다.
--
--     ALTER ROLE app WITH LOGIN PASSWORD '<환경별 비밀번호>';
--
--   이후 DATABASE_URL의 접속 유저·비밀번호를 postgres → app 으로 교체한다.
--     (스킴·호스트·포트·DB명은 그대로, userinfo 부분만 app:<비밀번호> 로)
--
--   재실행 불필요: 롤은 데이터베이스가 아니라 클러스터 단위 객체이고, 위 CREATE가
--   IF NOT EXISTS로 가드되므로 db:reset을 반복해도 LOGIN·비밀번호가 유지된다.
--
--   적용 이력 (환경별 — 적용 시 날짜를 채운다)
--     로컬   : supabase/seed.sql 이 db:reset 마다 자동 실행 (수동 조치 불필요)
--     베타   : 미적용
--     운영   : 미적용
--
--   근거·검증 항목: docs/architecture/db-authorization-review.md
-- ----------------------------------------------------------------------------

-- 스키마 USAGE = public 네임스페이스 진입 권한. 접근은 (스키마 USAGE + 테이블 권한) 둘 다 필요.
-- USAGE가 없으면 테이블 GRANT가 있어도 "permission denied for schema"로 막혀 무효(전제 관문).
-- 강화 환경(PG15+ / REVOKE ... FROM PUBLIC)에선 새 롤이 자동으로 못 받으므로 명시 부여.
-- CREATE는 주지 않음 — app은 기존 객체만 사용, 새 객체 생성은 소유자(마이그레이션)의 몫(최소권한).
GRANT USAGE ON SCHEMA public TO app;

-- REVOKE로 환경별 기본 권한을 비운 뒤(베이스라인), 아래에서 의도한 권한만 GRANT — 결과 결정적 고정
REVOKE ALL ON team, member, team_member, product, product_photo FROM anon, authenticated, app;
-- 읽기: 공개(Data API) + 앱(SSR 조회)
GRANT SELECT ON team, member, team_member, product, product_photo TO anon, authenticated, app;
-- 쓰기: 앱 롤만. admin 여부는 앱 DAL(modules/admin/lib/requireAdmin)이 판정한다.
GRANT INSERT, UPDATE, DELETE ON team, member, team_member, product, product_photo TO app;
