-- ============================================================================
-- init_order: 장바구니 · 주문 · 결제 도메인
--   - 금액: 전부 INT(원 단위, 음수 없음). 수량/금액 CHECK로 음수 방지.
-- ============================================================================

CREATE TABLE cart_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id UUID        NOT NULL,
    product_id BIGINT      NOT NULL,
    quantity   INT         NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE cart_item
    ADD CONSTRAINT cart_item_quantity_positive CHECK (quantity > 0);

CREATE UNIQUE INDEX cart_item_account_product_unique ON cart_item (account_id, product_id);
CREATE INDEX cart_item_product_idx ON cart_item (product_id);
CREATE INDEX cart_item_created_at_idx ON cart_item (created_at);
CREATE INDEX cart_item_updated_at_idx ON cart_item (updated_at);

COMMENT ON TABLE cart_item IS '장바구니 항목';
COMMENT ON COLUMN cart_item.id IS 'PK';
COMMENT ON COLUMN cart_item.account_id IS '회원 ID';
COMMENT ON COLUMN cart_item.product_id IS '상품 ID';
COMMENT ON COLUMN cart_item.quantity IS '수량';
COMMENT ON COLUMN cart_item.created_at IS '생성일';
COMMENT ON COLUMN cart_item.updated_at IS '수정일';

CREATE TABLE "order"
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no        TEXT        NOT NULL,
    account_id      UUID        NOT NULL,
    status          TEXT        NOT NULL,
    product_amount  INT         NOT NULL,
    discount_amount INT         NOT NULL,
    delivery_amount INT         NOT NULL,
    total_amount    INT         NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE "order"
    ADD CONSTRAINT order_amounts_non_negative
        CHECK (product_amount >= 0 AND discount_amount >= 0 AND delivery_amount >= 0 AND total_amount >= 0);

CREATE UNIQUE INDEX order_order_no_unique ON "order" (order_no);
CREATE INDEX order_account_created_at_idx ON "order" (account_id, created_at);
CREATE INDEX order_status_idx ON "order" (status);
CREATE INDEX order_created_at_idx ON "order" (created_at);
CREATE INDEX order_updated_at_idx ON "order" (updated_at);

COMMENT ON TABLE "order" IS '주문';
COMMENT ON COLUMN "order".id IS 'PK';
COMMENT ON COLUMN "order".order_no IS '주문번호';
COMMENT ON COLUMN "order".account_id IS '회원 ID';
COMMENT ON COLUMN "order".status IS '주문 상태';
COMMENT ON COLUMN "order".product_amount IS '상품 합계 금액(원)';
COMMENT ON COLUMN "order".discount_amount IS '할인 금액(원)';
COMMENT ON COLUMN "order".delivery_amount IS '배송비(원)';
COMMENT ON COLUMN "order".total_amount IS '최종 결제 금액(원)';
COMMENT ON COLUMN "order".created_at IS '생성일';
COMMENT ON COLUMN "order".updated_at IS '수정일';

CREATE TABLE order_no_seq
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seq_date   DATE        NOT NULL,
    seq        BIGINT      NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE order_no_seq
    ADD CONSTRAINT order_no_seq_positive CHECK (seq > 0);

CREATE UNIQUE INDEX order_no_seq_date_unique ON order_no_seq (seq_date);

COMMENT ON TABLE order_no_seq IS '주문번호 시퀀스';
COMMENT ON COLUMN order_no_seq.id IS 'PK';
COMMENT ON COLUMN order_no_seq.seq_date IS '채번 기준 날짜';
COMMENT ON COLUMN order_no_seq.seq IS '채번 시퀀스';
COMMENT ON COLUMN order_no_seq.created_at IS '생성일';
COMMENT ON COLUMN order_no_seq.updated_at IS '수정일';

CREATE TABLE order_item
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id              BIGINT      NOT NULL,
    product_id            BIGINT      NOT NULL,
    product_name          TEXT        NOT NULL,
    product_thumbnail_key TEXT,
    item_type             TEXT        NOT NULL,
    condition             TEXT,
    unit_price            INT         NOT NULL,
    quantity              INT         NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE order_item
    ADD CONSTRAINT order_item_quantity_positive CHECK (quantity > 0),
    ADD CONSTRAINT order_item_unit_price_non_negative CHECK (unit_price >= 0);

CREATE INDEX order_item_order_idx ON order_item (order_id);
CREATE INDEX order_item_product_idx ON order_item (product_id);
CREATE INDEX order_item_created_at_idx ON order_item (created_at);

COMMENT ON TABLE order_item IS '주문 상품';
COMMENT ON COLUMN order_item.id IS 'PK';
COMMENT ON COLUMN order_item.order_id IS '주문 ID';
COMMENT ON COLUMN order_item.product_id IS '상품 ID';
COMMENT ON COLUMN order_item.product_name IS '상품명';
COMMENT ON COLUMN order_item.product_thumbnail_key IS '썸네일 키';
COMMENT ON COLUMN order_item.item_type IS '아이템 유형';
COMMENT ON COLUMN order_item.condition IS '상품 상태';
COMMENT ON COLUMN order_item.unit_price IS '주문 시점 단가(원)';
COMMENT ON COLUMN order_item.quantity IS '수량';
COMMENT ON COLUMN order_item.created_at IS '생성일';

CREATE TABLE order_address
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT      NOT NULL,
    account_id       UUID        NOT NULL,
    recipient_name   TEXT        NOT NULL,
    recipient_phone  TEXT        NOT NULL,
    zipcode          TEXT        NOT NULL,
    base_address     TEXT        NOT NULL,
    detail_address   TEXT,
    delivery_message TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX order_address_order_unique ON order_address (order_id);
CREATE INDEX order_address_account_idx ON order_address (account_id);
CREATE INDEX order_address_created_at_idx ON order_address (created_at);

COMMENT ON TABLE order_address IS '배송지/연락처';
COMMENT ON COLUMN order_address.id IS 'PK';
COMMENT ON COLUMN order_address.order_id IS '주문 ID';
COMMENT ON COLUMN order_address.account_id IS '회원 ID';
COMMENT ON COLUMN order_address.recipient_name IS '수령인 이름';
COMMENT ON COLUMN order_address.recipient_phone IS '수령인 연락처';
COMMENT ON COLUMN order_address.zipcode IS '우편번호';
COMMENT ON COLUMN order_address.base_address IS '기본 주소';
COMMENT ON COLUMN order_address.detail_address IS '상세 주소';
COMMENT ON COLUMN order_address.delivery_message IS '배송 요청사항';
COMMENT ON COLUMN order_address.created_at IS '생성일';

CREATE TABLE payment
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT      NOT NULL,
    account_id       UUID        NOT NULL,
    order_no         TEXT        NOT NULL,
    provider         TEXT        NOT NULL,
    method           TEXT,
    status           TEXT        NOT NULL,
    requested_amount INT         NOT NULL,
    approved_amount  INT,
    trade_no         TEXT,
    approved_at      TIMESTAMPTZ,
    canceled_at      TIMESTAMPTZ,
    fail_message     TEXT,
    raw_request      JSONB,
    raw_response     JSONB,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE payment
    ADD CONSTRAINT payment_amounts_non_negative
        CHECK (requested_amount >= 0 AND approved_amount >= 0);

CREATE UNIQUE INDEX payment_trade_no_unique ON payment (trade_no) WHERE trade_no IS NOT NULL;
CREATE UNIQUE INDEX payment_order_unique ON payment (order_id);
CREATE INDEX payment_account_idx ON payment (account_id);
CREATE INDEX payment_order_no_idx ON payment (order_no);
CREATE INDEX payment_status_idx ON payment (status);
CREATE INDEX payment_created_at_idx ON payment (created_at);
CREATE INDEX payment_updated_at_idx ON payment (updated_at);

COMMENT ON TABLE payment IS '결제';
COMMENT ON COLUMN payment.id IS 'PK';
COMMENT ON COLUMN payment.order_id IS '주문 ID';
COMMENT ON COLUMN payment.account_id IS '회원 ID';
COMMENT ON COLUMN payment.order_no IS '주문번호';
COMMENT ON COLUMN payment.provider IS '결제 제공자';
COMMENT ON COLUMN payment.method IS '결제 수단';
COMMENT ON COLUMN payment.status IS '결제 상태';
COMMENT ON COLUMN payment.requested_amount IS '요청 금액(원)';
COMMENT ON COLUMN payment.approved_amount IS '승인 금액(원)';
COMMENT ON COLUMN payment.trade_no IS '거래번호';
COMMENT ON COLUMN payment.approved_at IS '승인 시각';
COMMENT ON COLUMN payment.canceled_at IS '취소 시각';
COMMENT ON COLUMN payment.fail_message IS '실패 메시지';
COMMENT ON COLUMN payment.raw_request IS '요청 원본';
COMMENT ON COLUMN payment.raw_response IS '응답 원본';
COMMENT ON COLUMN payment.created_at IS '생성일';
COMMENT ON COLUMN payment.updated_at IS '수정일';

CREATE TABLE order_status_history
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          BIGINT      NOT NULL,
    status            TEXT        NOT NULL,
    status_changed_at TIMESTAMPTZ NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX order_status_history_order_idx ON order_status_history (order_id, status_changed_at);
CREATE INDEX order_status_history_created_at_idx ON order_status_history (created_at);

COMMENT ON TABLE order_status_history IS '주문 상태 변경 이력';
COMMENT ON COLUMN order_status_history.id IS 'PK';
COMMENT ON COLUMN order_status_history.order_id IS '주문 ID';
COMMENT ON COLUMN order_status_history.status IS '주문 상태';
COMMENT ON COLUMN order_status_history.status_changed_at IS '상태 변경 시각';
COMMENT ON COLUMN order_status_history.created_at IS '생성일';

CREATE TABLE delivery_policy
(
    id                    BIGINT PRIMARY KEY,
    delivery_fee          INT         NOT NULL,
    free_threshold_amount INT,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE delivery_policy
    ADD CONSTRAINT delivery_policy_singleton CHECK (id = 1),
    ADD CONSTRAINT delivery_policy_fee_non_negative CHECK (delivery_fee >= 0),
    ADD CONSTRAINT delivery_policy_threshold_non_negative CHECK (free_threshold_amount >= 0);

INSERT INTO delivery_policy (id, delivery_fee, free_threshold_amount)
VALUES (1, 3000, NULL);

COMMENT ON TABLE delivery_policy IS '배송비 정책';
COMMENT ON COLUMN delivery_policy.id IS 'PK';
COMMENT ON COLUMN delivery_policy.delivery_fee IS '기본 배송비(원)';
COMMENT ON COLUMN delivery_policy.free_threshold_amount IS '무료 배송 기준(원)';
COMMENT ON COLUMN delivery_policy.created_at IS '생성일';
COMMENT ON COLUMN delivery_policy.updated_at IS '수정일';

-- ============================================================================
-- GRANT — app 롤만. 주문 기록은 정정하지 않고 이력으로 쌓으므로 대부분 DELETE 미부여.
--   - cart_item : 유일한 DELETE 부여 — 담았다 빼는 게 정상 동작인 임시 데이터
--   - order_item·order_address·order_status_history : INSERT 후 불변(주문 시점 스냅샷·이력)
--   - order·payment : 상태 전이가 있어 UPDATE까지
--   - delivery_policy : 단일 행(id=1)을 이 마이그레이션이 심는다 → INSERT 미부여(2행 방지)
--   - order_no_seq : 날짜별 채번기(도메인 데이터 아님). Postgres 시퀀스로는 날짜별 리셋이
--       안 돼 테이블로 구현 — 채번 시 INSERT/UPDATE 필요, 삭제는 불필요
-- ============================================================================
REVOKE ALL ON cart_item, "order", order_item, order_address, payment, order_status_history,
    delivery_policy, order_no_seq
    FROM anon, authenticated, app;

GRANT SELECT, INSERT, UPDATE, DELETE ON cart_item TO app;
GRANT SELECT, INSERT, UPDATE ON "order" TO app;
GRANT SELECT, INSERT ON order_item TO app;
GRANT SELECT, INSERT ON order_address TO app;
GRANT SELECT, INSERT, UPDATE ON payment TO app;
GRANT SELECT, INSERT ON order_status_history TO app;
GRANT SELECT, UPDATE ON delivery_policy TO app;
GRANT SELECT, INSERT, UPDATE ON order_no_seq TO app;
