-- ============================================================================
-- init_collection: 컬렉션 도메인
-- ============================================================================

CREATE TABLE inventory_item
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id            UUID        NOT NULL,
    product_id            BIGINT      NOT NULL,
    order_item_id         BIGINT      NOT NULL,
    product_name          TEXT        NOT NULL,
    product_thumbnail_key TEXT,
    item_type             TEXT        NOT NULL,
    team_id               BIGINT,
    member_id             BIGINT,
    quantity              INT         NOT NULL,
    acquired_at           TIMESTAMPTZ NOT NULL,
    reversed_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE inventory_item
    ADD CONSTRAINT inventory_item_quantity_positive CHECK (quantity > 0);

CREATE UNIQUE INDEX inventory_item_order_item_unique ON inventory_item (order_item_id);
CREATE INDEX inventory_item_account_product_idx ON inventory_item (account_id, product_id);
CREATE INDEX inventory_item_created_at_idx ON inventory_item (created_at);
CREATE INDEX inventory_item_updated_at_idx ON inventory_item (updated_at);

COMMENT ON TABLE inventory_item IS '보유 아이템';
COMMENT ON COLUMN inventory_item.id IS 'PK';
COMMENT ON COLUMN inventory_item.account_id IS '회원 ID';
COMMENT ON COLUMN inventory_item.product_id IS '상품 ID';
COMMENT ON COLUMN inventory_item.order_item_id IS '주문상품 ID';
COMMENT ON COLUMN inventory_item.product_name IS '상품명';
COMMENT ON COLUMN inventory_item.product_thumbnail_key IS '썸네일 키';
COMMENT ON COLUMN inventory_item.item_type IS '아이템 유형';
COMMENT ON COLUMN inventory_item.team_id IS '그룹 ID';
COMMENT ON COLUMN inventory_item.member_id IS '멤버 ID';
COMMENT ON COLUMN inventory_item.quantity IS '수량';
COMMENT ON COLUMN inventory_item.acquired_at IS '획득 시각(결제 시각)';
COMMENT ON COLUMN inventory_item.reversed_at IS '역산 시각(환불/취소)';
COMMENT ON COLUMN inventory_item.created_at IS '생성일';
COMMENT ON COLUMN inventory_item.updated_at IS '수정일';

CREATE TABLE collection
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id  UUID        NOT NULL,
    public_code TEXT        NOT NULL,
    title       TEXT        NOT NULL,
    is_public   BOOLEAN     NOT NULL DEFAULT FALSE,
    sort_order  INT         NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE collection
    ADD CONSTRAINT collection_sort_order_positive CHECK (sort_order > 0);

CREATE UNIQUE INDEX collection_public_code_unique ON collection (public_code);
CREATE INDEX collection_account_sort_order_idx ON collection (account_id, sort_order);
CREATE INDEX collection_created_at_idx ON collection (created_at);
CREATE INDEX collection_updated_at_idx ON collection (updated_at);

COMMENT ON TABLE collection IS '컬렉션';
COMMENT ON COLUMN collection.id IS 'PK';
COMMENT ON COLUMN collection.account_id IS '회원 ID';
COMMENT ON COLUMN collection.public_code IS '공개 URL';
COMMENT ON COLUMN collection.title IS '표시명';
COMMENT ON COLUMN collection.is_public IS '공개 여부';
COMMENT ON COLUMN collection.sort_order IS '노출 순번';
COMMENT ON COLUMN collection.created_at IS '생성일';
COMMENT ON COLUMN collection.updated_at IS '수정일';

CREATE TABLE collection_item
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    collection_id BIGINT      NOT NULL,
    product_id    BIGINT      NOT NULL,
    sort_order    INT         NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE collection_item
    ADD CONSTRAINT collection_item_sort_order_positive CHECK (sort_order > 0);

CREATE UNIQUE INDEX collection_item_collection_product_unique ON collection_item (collection_id, product_id);
CREATE INDEX collection_item_collection_sort_order_idx ON collection_item (collection_id, sort_order);
CREATE INDEX collection_item_product_idx ON collection_item (product_id);
CREATE INDEX collection_item_created_at_idx ON collection_item (created_at);
CREATE INDEX collection_item_updated_at_idx ON collection_item (updated_at);

COMMENT ON TABLE collection_item IS '컬렉션 항목';
COMMENT ON COLUMN collection_item.id IS 'PK';
COMMENT ON COLUMN collection_item.collection_id IS '컬렉션 ID';
COMMENT ON COLUMN collection_item.product_id IS '상품 ID';
COMMENT ON COLUMN collection_item.sort_order IS '노출 순번';
COMMENT ON COLUMN collection_item.created_at IS '생성일';
COMMENT ON COLUMN collection_item.updated_at IS '수정일';

REVOKE ALL ON inventory_item, collection, collection_item FROM anon, authenticated, app;
GRANT SELECT, INSERT, UPDATE ON inventory_item TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON collection TO app;
GRANT SELECT, INSERT, UPDATE, DELETE ON collection_item TO app;
